spring.application.name=demo
# Port ch?y Eureka Server
server.port=8761

# Không t? ??ng ký chính nó vào Eureka
eureka.client.register-with-eureka=false

# Không l?y danh sách service khác
eureka.client.fetch-registry=false

# T?t log riêng c?a Eureka
logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF
